version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
    volumes:
      - mysql-data:/var/lib/mysql


  spring-app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exo_matter_app
    ports:
      - "8000:8080"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PW: ${MYSQL_PW}

volumes:
  mysql-data:
    driver: local
